### ISSUE TITLE
bcgroundwater::get_gwl() bonks when *-minMaxMean.csv file has NAs

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/bcgroundwater#29]
`bcgroundwater::get_gwl(wells = 444)`

```
Retrieving data...
Formatting data...
Error in left_join_impl(x, y, by_x, by_y, aux_x, aux_y, na_matches) : 
  Can't join on 'dummydate' x 'dummydate' because of incompatible types (logical / character)
```

The *.minMaxMean.csv file for OW444 has NAs in the date column;the time series is less than 12 months to-date.

**Comment by ateucher** [comment]
@stephhazlitt would you expect to the result to still have the `Historical_Daily_Average`, `Historical_Daily_Minimum`, and `Historical_Daily_Maximum` columns (filled with `NA`) or just drop those columns entirely?

**Comment by stephhazlitt** [comment]
I lean to keeping the same API with `NAs` with the thought that there may be a downstream use or expectation in other `bcgroundwater` functions for those columns?

**Comment by ateucher** [comment]
Ok, I think that makes sense. Thanks

**Comment by ateucher** [comment]
Should work now!
