### ISSUE TITLE
Fix to work with new format of gwl data available in the B.C. Data Catalogue

### ISSUE THREAD

**Issue by ateucher** [bcgov/bcgroundwater#5]
http://www.env.gov.bc.ca/wsd/data_searches/obswell/map/index.html

**Comment by jayrbrown** [comment]
Notes from a user through efforts to run bcgroundwater.

There are 3 different files available for download from the source noted for the selected well. Data from one of 'recent' or 'data' source files should probably be merged with the 'minMaxMean' data to link up the historical values for reference.
- The two most recent calendar years of data ('recent' in filename)
- All available data ('data' in filename)
- Historical minimum, maximum, and mean values ('minMaxMean' in filename)

Vignette is not specific as to which dataset to use nor does it mention where to get the emsID. There is no emsID in the new data. The function does default to null emsID, but if that data is no longer available it should be removed altogether to avoid users trying to find out what it is.

It seems as though the path forward is to use one of the raw data files and create our own summary data for plotting. Pick up the well ID from the filename.

**Comment by ateucher** [comment]
Hi @jayrbrown, thanks very much for your notes; they will be very helpful when I go to rework this. The groundwater program has upgraded some of their database infrastructure and thus the outputs from the web tool have changed since we wrote this package/did the [analysis](https://github.com/bcgov/groundwater_levels).

I have added a note to the [README](https://github.com/bcgov/bcgroundwater/blob/master/README.md) reflecting this, but unfortunately I can't promise a timeline for when I can address the issue.

**Comment by jayrbrown** [comment]
Hi Andy,

Sorry for the edits. As I got deeper I learned more about it and realised I
said some dumb stuff that wasn't relevant. I'm working on an alternate data
load function that would format things the old way and hopefully will allow
the other functions to work. If I can make this work I'll do a PR and
thinking to call the function readGWLdata2. Just a band aid, really.

I think ultimately the changes to source data will substantially change how
it all works since the available data is quite different.

Cheers,
Jay

On Mon, Jun 8, 2015 at 10:03 AM, Andy Teucher notifications@github.com
wrote:

> Hi @jayrbrown https://github.com/jayrbrown, thanks very much for your
> notes; they will be very helpful when I go to rework this. The groundwater
> program has upgraded some of their database infrastructure and thus the
> outputs from the web tool have changed since we wrote this package/did the
> analysis https://github.com/bcgov/groundwater_levels.
> 
> I have added a note to the README
> https://github.com/bcgov/bcgroundwater/blob/master/README.md reflecting
> this, but unfortunately I can't promise a timeline for when I can address
> the issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bcgov/bcgroundwater/issues/5#issuecomment-110074198.

## 

Jay Brown
Senior Project Manager
Easy Metrics Inc.

Direct: 604.961.2762

**Comment by ateucher** [comment]
No need to apologize at all! I'm excited that you're interested (and I don't think you said anything dumb).  And you're right about having to change a lot of the code to deal with the changes. In a way, that's not a bad thing for me, as I want to rewrite a lot of it anyway in a better style.

That would be fantastic if you submit a PR. I will create a new branch for this bugfix that you can submit against.

**Comment by ateucher** [comment]
Hi @jayrbrown. I've create a new branch: [fix-newdata](https://github.com/bcgov/bcgroundwater/tree/fix-newdata). If you do get to working on this, please submit against that branch.

**Comment by jayrbrown** [comment]
Sounds great, Andy. I'm very excited to participate!

I think it's close and hopefully later this week I can get it done.

Jay

On Mon, Jun 8, 2015 at 10:21 AM, Andy Teucher notifications@github.com
wrote:

> Hi @jayrbrown https://github.com/jayrbrown. I've create a new branch:
> fix-newdata https://github.com/bcgov/bcgroundwater/tree/fix-newdata. If
> you do get to working on this, please submit against that branch.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bcgov/bcgroundwater/issues/5#issuecomment-110082208.

## 

Jay Brown
Senior Project Manager
Easy Metrics Inc.

Direct: 604.961.2762

**Comment by ateucher** [comment]
:+1:  Awesome!

**Comment by ateucher** [comment]
Merged #6 to deal with importing new data format - thanks @jayrbrown.  Will need to look at downstream workflow and assess changes required.

**Comment by stephhazlitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update package with indicator update (2018)](https://trello.com/c/KmNwT2Z2/8-update-package-with-indicator-update-2018)

**Comment by stephhazlitt** [comment]
Updating this issue.

Fix to work with data objects now available from the B.C. Data Catalogue under the Open Government Licence - British Columbia (https://catalogue.data.gov.bc.ca/dataset/provincial-groundwater-observation-well-network-groundwater-levels-data). Could be a single function to import one of or both available data objects or two functions, one per object. See [`rems` R package](https://github.com/bcgov/rems) for possible approach.

**Comment by steffilazerte** [comment]
Added new function `get_gwl`. Fixed with 824e72d
